[config]
# will be set to mainnet by default if omitted
# rpc = "https://fullnode.testnet.sui.io:443"
# rpc = "https://sui-testnet-endpoint.blockvision.org:443"
rpc = "https://rpc-testnet.suiscan.xyz:443"
# rpc = "https://sui-testnet.nodeinfra.com:443"

[packages]
# AccountMultisig = { git = "https://github.com/account-tech/move-registry.git", subdir = "packages/multisig", rev = "testnet" }
AccountProtocol = { local = "../../../../move-framework/packages/protocol" }
AccountPayment = { local = "../../../../move-registry/packages/payment" }
